export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_ANIMALS_PENDING = 'REQUEST_ANIMALS_PENDING';
export const REQUEST_ANIMALS_SUCCESS = 'REQUEST_ANIMALS_SUCCESS';
export const REQUEST_ANIMALS_FAILED = 'REQUEST_ANIMALS_FAILED';
